name: env-flow
on: [push]
jobs:
  outenv:
    env:
      connectionstring: "mysql.windows.database.com"
      password:  ${{secrets.password}}
    runs-on: ubuntu-latest
    steps:
      - name: outenv
        run: |
          echo "printing database endpoint ${{env.connectionstring}}"
          echo "database password ${{env.password}}"