name: "first flow"
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v3
      - name: "lrunning lint"
        run: echo "running lint"
      - name: "unit testing"
        run: echo "running unit testing"
      - name: "deploy"
        run: echo "running deploy"