name: "output flow"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{steps.outtask.outputs.filename}}
    steps:
      - name: "checkout code"
        uses: actions/checkout@v3
      - name: "lrunning lint"
        run: echo "running lint"
      - name: "unit testing"
        run: echo "running unit testing"
      - name: "deploy"
        run: echo "running deploy"
      - name: "outtask"
        id: "outtask"
        run: |
          filename=abcd.txt
          echo 'filename=$filename >> $GITHUB_OUTPUT

  out:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "outtask"
        run: echo "${{needs.build.outputs.filename}}"